latitude = 0.000000
longitude = 0.000000

[azimuth]
port = "/todo"
baud = 4800
index = 1
delta = 0.1

[elevation]
port = "/todo"
baud = 4800
index = 1
delta = 0.1

[imu]
port = "/todo"
baud = 9600
magnetic_declination = 0.0 # negative for west declination